### ISSUE TITLE
Where can I find this fcuntion: importR_ClusterVal_stats2 ??

### ISSUE THREAD

**Issue by legogeomin** [AndreasWunsch/Groundwater-Dynamic-Clustering#1]
@AndreasWunsch 

Hello!
 
I'm trying to using your code, but I'm encountering an error in this part. It says that the function 'importR_ClusterVal_stats2' does not exist.  I couldn't find this function in the Matlab functions, could you provide the code for this function?

% load chirp, sound(y,Fs)

clear
close all
tic
%% import R data
filename = 'C:\Users\Andreas Wunsch\Workspace\01_Matlab\R_ClusterVal_stats_FeatureConfig.txt';
eva = importR_ClusterVal_stats_2(filename);

%% load previous matlab data
load b_workspaceEnsemble_FeatureConfig

%% perform ensemble member ranking
for i = 1:5
   eva.(i) = round(eva{:,i},4); 
end

**Comment by AndreasWunsch** [comment]
Hi @minjiminji0762 , yeah you are right, this function is missing. Sorry about that. I am currently not able to retrieve the original function or write a new one. The easiest solution is to take the output file of 'ClusterStats_FeatureConfig.R' and write an import function in Matlab yourself. Just use the import tool, select all necessary options and click on 'save as function'. Shouldn't take more than a few minutes.
Best
